# app/config/application.yml
defaults: &defaults
  application:
    name: III Aquarii
    contact: riboulet@gmail.com
    root_dir: /Users
    repo_user: aq_git
    repo_git_path: git
    repo_hg_path: hg
    aq_shell: /Users/mcansky/Code/aquarii/aquarii-lib/aquarii-sh.rb
  logs:
    email: email.log


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

